version: '3'

services:
  server:
    image: 'ar2rworld/projects:main'
    restart: always
    environment:
      NOTIFICATOR_TOKEN: ${NOTIFICATOR_TOKEN}
      NOTIFICATOR_CHAT_ID: ${NOTIFICATOR_CHAT_ID}
