version: '3'

services:
  server:
    image: 'ar2rworld/projects:main'
    restart: always
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      KEYCLOAK_CLIENT_ID: ${KEYCLOAK_CLIENT_ID}
      KEYCLOAK_CLIENT_SECRET: ${KEYCLOAK_CLIENT_SECRET}
      KEYCLOAK_REALM: ${KEYCLOAK_REALM}
      KEYCLOAK_HOST: ${KEYCLOAK_HOST}
      KEYCLOAK_ADMIN_USERNAME: ${KEYCLOAK_ADMIN_USERNAME}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    networks:
      - projectsnetwork
    depends_on:
      - keycloak

  keycloak:
    image: quay.io/keycloak/keycloak:23.0.2
    environment:
      KC_DB: postgres
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin

      KC_DB_URL: jdbc:postgresql://${POSTGRES_HOST}:5432/${POSTGRES_DB}
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}

      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command:
      - 'start-dev'
    ports:
      - '8080:8080'
    networks:
      - projectsnetwork

networks:
  projectsnetwork:
    external: true
